/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.cs4474.wordtropolis.view;

import com.cs4474.wordtropolis.model.FireGameModel;
import com.cs4474.wordtropolis.model.Game;
import java.awt.GridLayout;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.awt.image.BufferedImage;
import java.net.URL;
import java.util.ArrayList;
import java.util.List;
import java.util.Random;
import javax.imageio.ImageIO;
import javax.swing.Timer;

/**
 *
 * @author svand
 */
public class testFire extends javax.swing.JPanel {

    private final FireGameModel model;
    private BufferedImage imgBg, imgHero, imgFireTruck;
    private BufferedImage imgFireStart, imgFireLoop, imgFireEnd;
    private final Random random = new Random();

    private static final int HERO_COLS = 4;
    private static final int HERO_FW = 210;   // frame width  (843 / 4)
    private static final int HERO_FH = 316;   // frame height (1264 / 4)
    private static final int HERO_BACK_ROW = 3;    // last row = back-facing walk
    private int heroFrame = 0;
    private Timer heroTimer;

    // 6 FlameLabel instances in a 3x2 grid for fire animations
    private List<FlameLabel> flames;

    private int fireCounter = 0; // Counter for extinguished fires
    private int fireIndex = 0;

    private StringBuilder currentInput = new StringBuilder();
    private String feedbackMsg = "";

    /**
     * Creates new form testFire
     */
    public testFire() {
        initComponents();

        this.setLayout(new GridLayout(2, 3, 10, 10));
        setUpKeyboard();

        model = new FireGameModel(Game.getInstance().getWordList());
        loadImages();
        initFires();
        this.counter.setText(fireCounter + "/6");
        this.curWord.setText(model.getCurrentWord());
        speakWord("The word on the window is " + model.getCurrentWord());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        counter = new javax.swing.JLabel();
        currInput = new javax.swing.JTextField();
        curWord = new javax.swing.JLabel();

        jButton1.setText("Submit");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        counter.setText("jLabel1");

        currInput.addActionListener(this::currInputActionPerformed);

        curWord.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(231, 231, 231)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(currInput, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addComponent(counter, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(curWord, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(252, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(333, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(counter)
                    .addComponent(curWord))
                .addGap(53, 53, 53)
                .addComponent(currInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addComponent(jButton1)
                .addGap(75, 75, 75))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        handleSubmit();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void currInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_currInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_currInputActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel counter;
    private javax.swing.JLabel curWord;
    private javax.swing.JTextField currInput;
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables

    private void setUpKeyboard() {
        setFocusable(true);
        requestFocusInWindow();

        addKeyListener(new KeyAdapter() {
            @Override
            public void keyTyped(KeyEvent e) {
                char c = e.getKeyChar();

                if (Character.isLetter(c)) {
                    currentInput.append(Character.toUpperCase(c));
                    repaint();
                }
            }

            @Override
            public void keyPressed(KeyEvent e) {
                int code = e.getKeyCode();

                if (code == KeyEvent.VK_BACK_SPACE && currentInput.length() > 0) {
                    currentInput.deleteCharAt(currentInput.length() - 1);
                    repaint();
                }

                if (code == KeyEvent.VK_ENTER) {
                    handleSubmit();
                }
            }
        });
    }

    private BufferedImage img(String path) {
        try {
            URL r = getClass().getResource(path);
            if (r == null) {
                System.out.println("[Fire] missing: " + path);
                return null;
            }
            return ImageIO.read(r);
        } catch (Exception e) {
            System.out.println("[Fire] err: " + path);
            return null;
        }
    }

    private void loadImages() {
        imgBg = img("/images/fire_game/building.png"); // Background image for Fire Game
        imgFireStart = img("/images/fire_game/fire_start.png");
        imgFireLoop = img("/images/fire_game/fire_loop.png");
        imgFireEnd = img("/images/fire_game/fire_end.png");
        imgFireTruck = img("/images/fire_game/fire_truck.png"); // Fire truck image

        // Load hero image based on avatar selection
        String avatarPath = Game.getInstance().getAvatarPath();
        if ("Mia".equalsIgnoreCase(avatarPath)) {
            imgHero = img("/images/general/hero1_standing.png");
        } else if ("Zyx".equalsIgnoreCase(avatarPath)) {
            imgHero = img("/images/general/alien_standing.png");
        } else {
            // Default: Alex / boy hero
            imgHero = img("/images/general/hero2_standing.png");
        }
    }

    private void initFires() {
        flames = new ArrayList<>();
        for (int i = 0; i < 6; i++) {
            FlameLabel flame = new FlameLabel(imgFireStart, imgFireLoop, imgFireEnd);
            flames.add(flame);
            add(flame);
            flame.ignite();
            System.out.println("Igniting " + i);
        }

        SoundManager.play(SoundManager.FIRE_IGNITE);
    }

    private void handleSubmit() {
        if (model.submitWord(this.currInput.getText())) {
            feedbackMsg = "Fire extinguished!";
            extinguishFire();

            if (fireCounter == 6) {
                this.curWord.setText("You extinguished all the fires!");
                speakWord("Congradulations. You did it.");
                SoundManager.play(SoundManager.FIRE_END_GAME);

            } else {
                model.pickNextWord();
                this.curWord.setText(model.getCurrentWord());

                speakWord("The word on the window is " + model.getCurrentWord());
            }

        } else {
            feedbackMsg = "Try again!";
            SoundManager.play(SoundManager.FIRE_ERROR);

            if (model.getWrongCount() > 4 && fireCounter > 0) {
                reigniteFire();
                model.resetWrongCount();
            }
        }
        currentInput.setLength(0);
        this.currInput.setText("");
        this.counter.setText(fireCounter + "/6");
        repaint();
    }

    // Update the fire counter
    private void updateFireCounter(int val) {
        if (val > 0) {
            fireCounter++;
        } else {
            fireCounter--;
        }

        int i = (fireIndex == 5) ? 0 : fireIndex;
        for (; i < 6; i++) {
            if (flames.get(i).isActive()) {
                fireIndex = i;
                break;
            }
        }
        repaint();
    }

    // Handle fire extinguishing logic (extinguish the fire when necessary)
    private void extinguishFire() {
        if (fireIndex >= 0 && fireIndex < flames.size()) {
            flames.get(fireIndex).extinguish(); // Play the end animation for this fire

            System.out.println("extinguish " + fireIndex + "\n");
            updateFireCounter(1); // Increment the counter when the fire is extinguished
            SoundManager.play(SoundManager.FIRE_HOSE);
        }
    }

    // Handle reigniting logic (allow fires to be reignited after extinguishing)
    private void reigniteFire() {
        updateFireCounter(-1);
        System.out.println("reigniting...");

        boolean ignite = true;
        int i;

        while (ignite) {
            i = random.nextInt(6);
            System.out.println("Checking " + i);
            if (!flames.get(i).isActive()) {
                flames.get(i).ignite(); // Reignite the fire and start the loop animation
                System.out.println("reigniting " + i + "\n");
                ignite = false;
            }
        }
        SoundManager.play(SoundManager.FIRE_IGNITE);
    }

    // Helper method to trigger word pronunciation (same as in the CatGame)
    private void speakWord(String w) {
        if (w == null || w.isEmpty()) {
            return;
        }

        new Thread(() -> {
            try {
                String os = System.getProperty("os.name", "").toLowerCase();

                if (os.contains("mac")) {
                    new ProcessBuilder("say", "-v", "Alex", "-r", "110", "[[volm 1.0]] " + w)
                            .start().waitFor();
                } else if (os.contains("win")) {
                    String ps = "Add-Type -AssemblyName System.Speech;"
                            + "$s = New-Object System.Speech.Synthesis.SpeechSynthesizer;"
                            + "$s.Rate = -2;"
                            + "$s.Volume = 100;"
                            + "$s.Speak('" + w.replace("'", "") + "');";
                    new ProcessBuilder("powershell", "-Command", ps)
                            .start().waitFor();
                } else {
                    new ProcessBuilder("espeak", "-s", "120", "-a", "200", w)
                            .start().waitFor();
                }
            } catch (Exception e) {
                System.out.println("[Fire] TTS not available: " + e.getMessage());
            }
        }, "tts-thread").start();
    }

}
